import cloneDeep from 'lodash/cloneDeep'
import { workItemsTypes } from '@/views/workbench/constant'

const tableFields = [
  {
    attrName: 'priority',
    attrText: '单选框',
    attrType: 10,
    attrValue: 'SINGLE_CHOICE',
    codeDisplayName: '优先级',
    dataSource: 'WorkItemPriority',
    defaultValueTypeOptions: [],
    displayAttrName: 'priority',
    fieldName: '优先级',
    hiddenWhenCreate: false,
    hideable: false,
    nameCode: 'WorkItemField.PRIORITY',
    optional: false,
    presetValue: '{"key":80,"value":"P2"}',
    readonly: false,
    required: true,
    sortable: true,
    systemAttr: true,
  },
  {
    attrName: 'startTime',
    attrText: '简单时间框(不包含时分秒)',
    attrType: 5,
    attrValue: 'LITE_DATE_ATTR',
    codeDisplayName: '开始时间',
    defaultValueTypeOptions: [],
    displayAttrName: 'startTime',
    fieldName: '开始时间',
    hiddenWhenCreate: false,
    hideable: false,
    nameCode: 'WorkItemField.START_TIME',
    optional: true,
    readonly: false,
    required: false,
    sortable: true,
    systemAttr: true,
  },
  {
    attrName: 'endTime',
    attrText: '简单时间框(不包含时分秒)',
    attrType: 5,
    attrValue: 'LITE_DATE_ATTR',
    codeDisplayName: '结束时间',
    defaultValueTypeOptions: [],
    displayAttrName: 'endTime',
    fieldName: '结束时间',
    hiddenWhenCreate: false,
    hideable: false,
    nameCode: 'WorkItemField.END_TIME',
    optional: true,
    readonly: false,
    required: false,
    sortable: true,
    systemAttr: true,
  },
  {
    attrName: 'finishTime',
    attrText: '详情时间框(包含时分秒)',
    attrType: 6,
    attrValue: 'DATE_ATTR',
    codeDisplayName: '实际完成时间',
    defaultValueTypeOptions: [],
    displayAttrName: 'finishTime',
    fieldName: '实际完成时间',
    hiddenWhenCreate: true,
    hideable: false,
    nameCode: 'WorkItemField.REQT_FINISH_TIME',
    optional: false,
    readonly: true,
    required: false,
    sortable: true,
    systemAttr: true,
  },
  {
    attrName: 'projectName',
    attrText: '成员单选框',
    attrType: 3,
    attrValue: 'MEMBER_CHOICE',
    codeDisplayName: 'projectName',
    dataSource: 'Member',
    defaultValueTypeOptions: [],
    displayAttrName: 'projectName',
    fieldName: '项目名称',
    hiddenWhenCreate: true,
    hideable: false,
    nameCode: 'WorkItemField.CREATE_USER',
    optional: false,
    readonly: true,
    required: true,
    sortable: true,
    systemAttr: true,
  }, // 项目
  {
    attrName: 'sprintId',
    attrText: '单选框',
    attrType: 10,
    attrValue: 'SINGLE_CHOICE',
    codeDisplayName: '迭代',
    dataSource: 'Sprint',
    defaultValueTypeOptions: [],
    displayAttrName: 'sprint',
    fieldName: '迭代',
    hiddenWhenCreate: false,
    hideable: false,
    nameCode: 'WorkItemField.SPRINT',
    optional: true,
    presetValue: '{"key":0,"value":"未规划"}',
    readonly: false,
    required: false,
    sortable: true,
    systemAttr: true,
  },
  {
    attrName: 'assignUser',
    attrText: '成员单选框',
    attrType: 10,
    attrValue: 'MEMBER_CHOICE',
    codeDisplayName: '处理人',
    dataSource: 'Member',
    defaultValueTypeOptions: [],
    displayAttrName: 'assignUser',
    fieldName: '处理人',
    hiddenWhenCreate: false,
    hideable: false,
    nameCode: 'WorkItemField.REQT_ASSIGN_TO',
    optional: false,
    readonly: false,
    required: true,
    sortable: true,
    systemAttr: true,
  },
  {
    attrName: 'statusId',
    attrText: '单选框',
    attrType: 10,
    attrValue: 'SINGLE_CHOICE',
    codeDisplayName: '状态',
    dataSource: 'WorkItemStatus',
    defaultValueTypeOptions: [],
    displayAttrName: 'status',
    fieldName: '状态',
    hiddenWhenCreate: true,
    hideable: false,
    nameCode: 'WorkItemField.STATUS',
    optional: false,
    readonly: false,
    required: true,
    sortable: true,
    systemAttr: true,
  },
]

function getTableFields(workItemsType) {
  const fields = []
  tableFields.forEach(item => {
    if (
      workItemsTypes.MY_DONE === workItemsType ||
      workItemsTypes.MY_DONE_OF_TODAY === workItemsType
    ) {
      fields.push(cloneDeep(item))
    } else if (item.attrName !== 'finishTime') {
      fields.push(cloneDeep(item))
    }
  })
  return fields
}

export { getTableFields }
