/**
 * @title 常量
 * @author chenxiaolong
 * @date 2021.4.14
 */
import { WORKITEMCONST } from '@/utils/constant'
const { workItemTypeMap } = WORKITEMCONST
export const workItems = [
  {
    key: workItemTypeMap.requirement,
    name: '需求',
  },
  {
    key: workItemTypeMap.task,
    name: '任务',
  },
  {
    key: workItemTypeMap.bug,
    name: '缺陷',
  },
]

export const workItemNames = {
  [workItemTypeMap.requirement]: '需求',
  [workItemTypeMap.task]: '任务',
  [workItemTypeMap.bug]: '缺陷',
}

// 头部搜索条件
export const topFilterFields = [
  {
    attrName: 'searchKey',
    attrValue: 'SINGLE_TEXT',
    fieldName: '',
    formType: 'INPUT',
    value: '',
    attrs: {
      'suffix-icon': 'el-icon-search',
      placeholder: '请输入关键字',
    },
  },
  {
    attrName: 'workItemType',
    attrValue: 'MULTI_CHOICE',
    fieldName: '工作项类型',
    formType: 'CHECKBOX',
    value: ['all'],
    selectList: [
      {
        value: '需求',
        label: '需求',
        key: 1,
      },
      {
        value: '任务',
        label: '任务',
        key: 2,
      },
      {
        value: '缺陷',
        label: '缺陷',
        key: 3,
      },
    ],
    filterField: false,
    popperAppendToBody: true,
    isClearable: false,
    isAssignUser: false,
    attrs: {
      'collapse-tags': true,
      clearAll: true,
      pickAll: true,
      multiple: true,
    },
  },
  {
    attrName: 'projectId',
    attrValue: 'MULTI_CHOICE_SEARCH',
    fieldName: '项目',
    dataSource: 'project',
    formType: 'SELECT',
    value: ['all'],
    selectList: [],
    filterField: false,
    popperAppendToBody: true,
    isClearable: false,
    isAssignUser: false,
    attrs: {
      clearAll: true,
      pickAll: true,
      multiple: true,
      loading: true,
      'collapse-tags': true,
      group: true,
    },
  },
  {
    attrName: 'sprintId',
    attrValue: 'MULTI_CHOICE_SEARCH',
    fieldName: '迭代',
    dataSource: 'sprint',
    formType: 'SELECT',
    value: ['all'],
    selectList: [],
    filterField: false,
    popperAppendToBody: true,
    isClearable: false,
    isAssignUser: false,
    attrs: {
      clearAll: true,
      pickAll: true,
      multiple: true,
      loading: true,
      'collapse-tags': true,
      group: true,
    },
  },
  {
    attrName: 'assignUser',
    attrValue: 'MULTI_MEMBER_CHOICE',
    fieldName: '处理人',
    formType: 'SELECT',
    dataSource: 'Member',
    value: ['all'],
    selectList: [],
    filterField: false,
    popperAppendToBody: true,
    isClearable: false,
    isAssignUser: true,
    attrs: {
      clearAll: true,
      pickAll: true,
      multiple: true,
      loading: true,
      'collapse-tags': true,
      group: false,
    },
  },
]

export const queryOptions = {
  priority: {
    attrName: 'prioritys',
    dataSource: 'priority',
  },
  createUser: {
    attrName: 'assignUsers',
    dataSource: 'Member',
  },
  expectedSolutionPhase: {
    attrName: 'expectedSolutionPhases',
    dataSource: 'expectedSolutionPhase',
  },
  relevantUser: {
    attrName: 'relevantUsers',
    dataSource: 'relevantUser',
  },
  categoryId: {
    attrName: 'categoryIds',
    dataSource: 'categoryId',
  },
}

export const statusList = [
  {
    attrName: 'requireStatusIds',
    attrValue: 'MULTI_CHOICE_SEARCH',
    fieldName: '需求状态',
    formType: 'SELECT',
    value: ['all'],
    selectList: [],
    dataSource: 'requirementStatus',
    filterField: false,
    popperAppendToBody: true,
    workItemType: 1,
    isClearable: false,
    isAssignUser: false,
    attrs: {
      clearAll: true,
      pickAll: true,
      multiple: true,
      loading: true,
      'collapse-tags': true,
      group: false,
    },
  },
  {
    attrName: 'taskStatusIds',
    attrValue: 'MULTI_CHOICE_SEARCH',
    fieldName: '任务状态',
    formType: 'SELECT',
    workItemType: 2,
    value: ['all'],
    selectList: [],
    dataSource: 'taskStatus',
    filterField: false,
    popperAppendToBody: true,
    isClearable: false,
    isAssignUser: false,
    attrs: {
      clearAll: true,
      pickAll: true,
      multiple: true,
      loading: true,
      'collapse-tags': true,
      group: false,
    },
  },
  {
    attrName: 'defectStatusIds',
    attrValue: 'MULTI_CHOICE_SEARCH',
    fieldName: '缺陷状态',
    formType: 'SELECT',
    workItemType: 3,
    value: ['all'],
    selectList: [],
    dataSource: 'defectStatus',
    filterField: false,
    popperAppendToBody: true,
    isClearable: false,
    isAssignUser: false,
    attrs: {
      clearAll: true,
      pickAll: true,
      multiple: true,
      loading: true,
      'collapse-tags': true,
      group: false,
    },
  },
  {
    attrName: 'createTime',
    attrValue: 'LITE_DATE_RANGE_ATTR',
    fieldName: '创建时间',
    formType: 'DATE_PICKER',
    value: [],
    selectList: [],
    filterField: false,
    popperAppendToBody: true,
    isClearable: false,
    isAssignUser: false,
    attrs: {
      'start-placeholder': '开始日期',
      'end-placeholder': '结束日期',
    },
  },
]

// 更多筛选条件
export const moreFilterFields = [
  {
    attrName: 'priority',
    attrValue: 'MULTI_CHOICE_SEARCH',
    fieldName: '优先级/严重程度',
    dataSource: 'priority',
    formType: 'SELECT',
    value: ['all'],
    selectList: [],
    filterField: false,
    popperAppendToBody: true,
    isClearable: false,
    isAssignUser: false,
    attrs: {
      clearAll: true,
      pickAll: true,
      multiple: true,
      loading: true,
      'collapse-tags': true,
      group: false,
    },
  },

  ...statusList,
  {
    attrName: 'createUser',
    attrValue: 'MULTI_MEMBER_CHOICE',
    fieldName: '创建人',
    formType: 'SELECT',
    dataSource: 'Member',
    value: ['all'],
    selectList: [],
    filterField: false,
    popperAppendToBody: true,
    isClearable: false,
    isAssignUser: true,
    attrs: {
      clearAll: true,
      pickAll: true,
      multiple: true,
      loading: true,
      'collapse-tags': true,
      group: false,
    },
  },

  {
    attrName: 'startTime',
    attrValue: 'LITE_DATE_RANGE_ATTR',
    fieldName: '开始时间',
    formType: 'DATE_PICKER',
    value: [],
    selectList: [],
    filterField: false,
    popperAppendToBody: true,
    isClearable: false,
    isAssignUser: false,
    attrs: {
      'start-placeholder': '开始日期',
      'end-placeholder': '结束日期',
    },
  },
  {
    attrName: 'endTime',
    attrValue: 'LITE_DATE_RANGE_ATTR',
    fieldName: '结束时间',
    formType: 'DATE_PICKER',
    value: [],
    selectList: [],
    filterField: false,
    popperAppendToBody: true,
    isClearable: false,
    isAssignUser: false,
    attrs: {
      'start-placeholder': '开始日期',
      'end-placeholder': '结束日期',
    },
  },
]

export const defaultHeaderCustomFields = [
  {
    fieldName: '优先级',
    nameCode: 'WorkItemField.DFCT_PRIORITY',
    attrName: 'priority',
    attrType: 10,
    attrText: '单选框',
    attrValue: 'SINGLE_CHOICE',
    required: true,
    readonly: false,
    sortable: true,
    presetValue: '{"key":80,"value":"普通"}',
    systemAttr: true,
    hideable: false,
    optional: false,
    hiddenWhenCreate: false,
    dataSource: 'WorkItemPriority',
    defaultValueTypeOptions: [],
    codeDisplayName: '严重程度',
  },

  {
    fieldName: '迭代',
    nameCode: 'WorkItemField.SPRINT',
    attrName: 'sprintId',
    displayAttrName: 'sprint',
    attrType: 10,
    attrText: '单选框',
    attrValue: 'SINGLE_CHOICE',
    required: false,
    readonly: false,
    sortable: true,
    presetValue: '{"key":0,"value":"未规划"}',
    systemAttr: true,
    hideable: true,
    optional: true,
    hiddenWhenCreate: false,
    dataSource: 'Sprint',
    defaultValueTypeOptions: [],
    codeDisplayName: '迭代',
  },
  {
    fieldName: '状态',
    nameCode: 'WorkItemField.STATUS',
    attrName: 'statusId',
    displayAttrName: 'status',
    attrType: 10,
    attrText: '单选框',
    attrValue: 'SINGLE_CHOICE',
    required: true,
    readonly: false,
    sortable: true,
    systemAttr: true,
    hideable: false,
    optional: false,
    hiddenWhenCreate: true,
    dataSource: 'WorkItemStatus',
    defaultValueTypeOptions: [],
    codeDisplayName: '状态',
  },
  {
    fieldName: '处理人',
    nameCode: 'WorkItemField.ASSIGN_USER',
    attrName: 'assignUser',
    attrType: 3,
    attrText: '成员单选框',
    attrValue: 'MEMBER_CHOICE',
    required: true,
    readonly: false,
    sortable: true,
    systemAttr: true,
    hideable: false,
    optional: false,
    hiddenWhenCreate: false,
    dataSource: 'Member',
    defaultValueTypeOptions: [],
    codeDisplayName: '处理人',
  },
  {
    fieldName: '所属项目',
    nameCode: 'WorkItemField.ASSIGN_USER',
    attrName: 'projectName',
    attrText: '所属项目',
    attrValue: 'DATE_ATTR',
    required: false,
    readonly: true,
    sortable: true,
    systemAttr: true,
    hideable: false,
    optional: false,
    hiddenWhenCreate: false,
    defaultValueTypeOptions: [],
    codeDisplayName: '所属项目',
  },
  {
    fieldName: '开始时间',
    nameCode: 'WorkItemField.DFCT_CREATE_TIME',
    attrName: 'startTime',
    attrType: 6,
    attrText: '详情时间框(包含时分秒)',
    attrValue: 'LITE_DATE_ATTR',
    required: false,
    readonly: false,
    sortable: true,
    systemAttr: true,
    hideable: false,
    optional: true,
    hiddenWhenCreate: false,
    defaultValueTypeOptions: [],
    codeDisplayName: '开始时间',
    displayAttrName: 'startTime',
  },

  {
    fieldName: '结束时间',
    nameCode: 'WorkItemField.DFCT_CREATE_TIME',
    attrName: 'endTime',
    attrType: 6,
    attrText: '详情时间框(包含时分秒)',
    attrValue: 'LITE_DATE_ATTR',
    required: false,
    readonly: false,
    sortable: true,
    systemAttr: true,
    hideable: false,
    optional: true,
    hiddenWhenCreate: false,
    defaultValueTypeOptions: [],
    codeDisplayName: '结束时间',
    displayAttrName: 'endTime',
  },

  {
    fieldName: '创建人',
    nameCode: 'WorkItemField.ASSIGN_USER',
    attrName: 'createUser',
    attrType: 3,
    attrText: '成员单选框',
    attrValue: 'MEMBER_CHOICE',
    required: true,
    readonly: true,
    sortable: true,
    systemAttr: true,
    hideable: false,
    optional: false,
    hiddenWhenCreate: false,
    dataSource: 'Member',
    defaultValueTypeOptions: [],
    codeDisplayName: '处理人',
    displayAttrName: 'createUser',
  },
  {
    fieldName: '创建时间',
    nameCode: 'WorkItemField.CREATE_TIME',
    attrName: 'createTime',
    attrType: 6,
    attrText: '详情时间框(包含时分秒)',
    attrValue: 'DATE_ATTR',
    required: false,
    readonly: true,
    sortable: true,
    systemAttr: false,
    hideable: true,
    optional: true,
    hiddenWhenCreate: true,
    defaultValueTypeOptions: [],
    codeDisplayName: '创建时间',
    displayAttrName: 'createTime',
  },
]
